Estos son los ejercicios que estuve haciendo de python
Ulimart/python pull request #6
Opened 2022-10-26 17:54 UTC by Caro-Love21

Acabo de subir ejercicios de python para que veas lo que he hecho, aún sigo trabajando.

2022-10-26 19:23 UTC, Caro-Love21 reviewed
Seguiré subiendo teoría de git, que es lo que me está costando entender.

2022-10-26 21:42 UTC, Ulimart requested changes
Vamos a organizar las carpetas para poder aceptar el PR

2022-10-26 21:42 UTC, Ulimart commented on python_exercises/comandos_git.md
> +                                        COMANDOS GIT
Cambiemos todo lo de git a una carpeta que sea solo de Git junto con los md

2022-10-26 21:42 UTC, Ulimart commented on python_exercises/teoria_01.md
> +                                                    GIT:
Lo mismo pasalo a una carpeta solo de git

2022-10-27 20:21 UTC, Caro-Love21 commented on python_exercises/comandos_git.md
> +                                        COMANDOS GIT
ya creé la nueva carpeta de git y agregué toda info allá, así como eliminé los archivos que tenía en la carpeta de python

2022-10-27 20:21 UTC, Caro-Love21 commented on python_exercises/teoria_01.md
> +                                                    GIT:
Done

2022-10-27 20:23 UTC, closed without merging